namespace OpenApi.Builders

open Microsoft.OpenApi.Models

type SecuritySchemeBuilder () =

    member _.Yield _ =
        OpenApiSecurityScheme ()

    /// REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
    [<CustomOperation "type">]
    member _.Type (state: OpenApiSecurityScheme, value) =
        state.Type <- value
        state

    /// REQUIRED. The name of the header, query or cookie parameter to be used.
    [<CustomOperation "name">]
    member _.Name (state: OpenApiSecurityScheme, value) =
        state.Name <- value
        state

    /// REQUIRED. The location of the API key. Valid values are "query", "header" or "cookie".
    [<CustomOperation "in">]
    member _.In (state: OpenApiSecurityScheme, value) =
        state.In <- value
        state

    /// REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
    /// The values used SHOULD be registered in the IANA Authentication Scheme registry.
    [<CustomOperation "scheme">]
    member _.Scheme (state: OpenApiSecurityScheme, value) =
        state.Scheme <- value
        state

    /// REQUIRED. An object containing configuration information for the flow types supported.
    [<CustomOperation "flows">]
    member _.Flows (state: OpenApiSecurityScheme, value) =
        state.Flows <- value
        state

    /// REQUIRED. OpenId Connect URL to discover OAuth2 configuration values.
    [<CustomOperation "openIdConnectUrl">]
    member _.OpenIdConnectUrl (state: OpenApiSecurityScheme, value) =
        state.OpenIdConnectUrl <- value
        state


    /// A short description for security scheme. CommonMark syntax.
    [<CustomOperation "description">]
    member _.Description (state: OpenApiSecurityScheme, value) =
        state.Description <- value
        state

    /// A hint to the client to identify how the bearer token is formatted.
    /// Bearer tokens are usually generated by an authorization server,
    /// so this information is primarily for documentation purposes.
    [<CustomOperation "bearerFormat">]
    member _.BearerFormat (state: OpenApiSecurityScheme, value) =
        state.BearerFormat <- value
        state

    [<CustomOperation "addExtension">]
    member _.Extensions (state: OpenApiSecurityScheme, key, value) =
        state.Extensions.Add (key, value)
        state

    [<CustomOperation "unresolvedReference">]
    member _.UnresolvedReference (state: OpenApiSecurityScheme, value) =
        state.UnresolvedReference <- value
        state

    [<CustomOperation "reference">]
    member _.Reference (state: OpenApiSecurityScheme, value) =
        state.Reference <- value
        state
